[project]
name = "bulle-planning-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "chardet>=5.2.0",
    "loguru>=0.7.3",
    "pydantic>=2.11.7",
]
